[project]
name = 'fundx'
description = 'FundX escrow contract powered by USDCx'
authors = []
telemetry = false
cache_dir = './.cache'

# [[project.requirements]]
[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[contracts.fundx-escrow-v2]
path = 'contracts/fundx-escrow.clar'
clarity_version = 2
epoch = 'latest'

[contracts.indiegogo-v2]
path = 'contracts/indiegogo.clar'
clarity_version = 2
epoch = 'latest'

[contracts.sip-010-trait-v2]
path = 'contracts/sip-010-trait-ft-standard.clar'
clarity_version = 2
epoch = 'latest'

[contracts.usdcx-v2]
path = 'contracts/usdcx-mock.clar'
clarity_version = 2
epoch = 'latest'


[repl.analysis]
passes = ['check_checker', 'call_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
api_url = 'https://api.hiro.so'